[meta title:"{PROJECT_TITLE}" description:"Short description of your project" /]

[Header
  title:"{PROJECT_TITLE}"
  subtitle:"Welcome to Literasee, powered by Idyll"
  author:"{AUTHOR}"
  authorLink:"{AUTHOR_LINK}" /]

This is an Idyll file. Write text
as you please in here. To add interactivity,
you can add different components to the text.

Here is how you can use a variable:

[var name:"exampleVar" value: 5 /]

[Range min:0 max:10 value:exampleVar /]
[DisplayVar var:exampleVar /]

You can use standard html tags if a
component with the same name
doesn't exist.

You can also include code samples.

```js
function thisIsSoEasy() {
  return 'Yes. Yes it is.'
}
```
